### ISSUE TITLE
Property `CreatePrismaRedisCache.models.excludeMethods` not work

### ISSUE THREAD

**Issue by cy948** [Asjas/prisma-redis-middleware#165]
**Describe the bug**
Still cache for Prisma query actions even set property in `CreatePrismaRedisCache.models.excludeMethods` 

**To Reproduce**
1. Setup options like this

- schema.prisma
```
model User {

}
```

```typescript
prismaClient.$use(
  createPrismaRedisCache({
    models: [
      { model: "User", cacheTime: 60, excludeMethods: ['findFirst']},  // not work as expected
    ]
// ..other options
})
```
3. See error
still cache for method `findFirst`

```log
onHit {"params":{"action":"findFirst","args":{"where":{"id":""}},"dataPath":[],"model":"User","runInTransaction":false}}
```

**Expected behavior**
not cache for `findFirst` method

**Screenshots**

log in dashboard
![image](https://user-images.githubusercontent.com/67412196/173408519-9c2c6c64-dc8d-4c37-bea3-e7b65ec31045.png)

**Runtime (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Version NodeJs `v16.14.1`

**Additional context**
```package.json
    "@prisma/client": "^3.12.0",
    "prisma-redis-middleware": "3.3.0",
    "prisma": "^3.12.0",
```

**Comment by Asjas** [comment]
I ran the test suite and I can't get it to cache the `findUnique` method if it's been excluded. I can't replicate the issue.

![Screenshot 2022-07-07 at 13 02 28](https://user-images.githubusercontent.com/3828967/177759054-84ca1bc3-78ab-4eaf-ad83-ea995ec05a0a.png)

**Comment by Asjas** [comment]
Fixed in https://github.com/Asjas/prisma-redis-middleware/releases/tag/v4.0.7
