### ISSUE TITLE
update cache when database gets updated

### ISSUE THREAD

**Issue by tekoh** [Asjas/prisma-redis-middleware#192]
so i'm not sure if this is intended or not, but when fetching data the cache works fine, but when you then update that data, the cache still exists so when you fetch again, you get out of date data.

any chance this could be added? i thought it would be an expected feature

**Comment by Asjas** [comment]
There is basic cache invalidation where all data related to a Model will be removed from the cache if the data related to that Model is updated. 🙂 

Can you post your Prisma model, code, a minimum reproduction, anything? I would need to see what you are doing and why it isn't working.

**Comment by tekoh** [comment]
quick script i made: https://pastebin.com/idnc2rmU

the output: 
![image](https://user-images.githubusercontent.com/29782397/179428580-7dbabac0-c75c-4804-8dd1-21bac2708d01.png)
starting balance was 69420, gets updated to 6666666, but still stays as 69420 on second select

and here is the model for that table:
![image](https://user-images.githubusercontent.com/29782397/179428626-e6c957e1-e94c-47d6-af0c-6587c26b9885.png)

**Comment by Asjas** [comment]
Fixed in https://github.com/Asjas/prisma-redis-middleware/releases/tag/v4.0.7
