### ISSUE TITLE
Support for Node 18

### ISSUE THREAD

**Issue by AlanMorel** [Asjas/prisma-redis-middleware#206]
I'm unable to add this project because it's missing Node 18 as one of the engines.

```
error prisma-redis-middleware@4.0.8: The engine "node" is incompatible with this module. Expected version "^14.x || ^16.x". Got "18.0.0"
error Found incompatible module.
```
Would love to see it added/updated, thank you!

**Comment by Asjas** [comment]
Fixed in https://github.com/Asjas/prisma-redis-middleware/releases/tag/v4.1.0 👍
