### ISSUE TITLE
Cache not beeing updated

### ISSUE THREAD

**Issue by Tomato6966** [Asjas/prisma-redis-middleware#234]
My method:
```js
await prisma.settings.upsert({
    where: { 
        guildId: message.guildId
    },
    create: getDefaultSettingsData(message.guildId, {prefix: args[0]}),
    update: { prefix: args[0] },
}).catch(console.error)
```

My setup:
```js
prisma.$use(createPrismaRedisCache({...cacheData, storage: { 
  type: "redis",
  models: [
    { model: "Settings" },
  ],
  cacheTime: 1300, 
  excludeCacheMethods: ["findMany"],
  options: { 
    client: redis, invalidation: { referencesTTL: 3600, size: 1000000 }
  }
}}));
```

My model:
```js
model Settings {
  guildId                String         @id
  prefix                 String
  botchannels            String[] // on lists there cant be default
  language               Languages      @default(en)
  alldaymusic            String         @default("disabled") // "disabled" || "{ channel: '', link: '' }"
  defaultvolume          Int            @default(100)
  defaultautoplay        Boolean        @default(true)
  allowyoutube           Boolean        @default(false)
  defaultsearchplattform SearchPlatform @default(ytm)
  extraData              String? // can be anything inside a JSON.stringify({});
}
```

Now when i call the upsert (update) method
It's not updating the redis-cache and still pulling OLD CACHE DATA..

meaning if prefix was before: "!" and i change it to "$" in the db it says "$" but when i do:
```js
const data = await prisma.settings.findFirst({
  where: {
    guildId: message.guildId
  },
  select: {
    prefix: true, otheroptions
  }
});
```
the `data.prefix` still says it's "!"

![image](https://user-images.githubusercontent.com/68145571/187184295-1991a821-65e5-4ba8-b668-e6c6091480ee.png)
![image](https://user-images.githubusercontent.com/68145571/187184282-ea49e7d2-da5b-4c34-994a-fce70e5a07df.png)

It only does not work when i fetch multiple fields at the same time....
what could be the problem for that?!?!

**Comment by Asjas** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Tomato6966** [comment]
I can explain... And i know the issue
the issue is at:  

![image](https://user-images.githubusercontent.com/68145571/187185571-c9b4e73e-350e-430b-8597-4b039f1a2206.png)


As you can see from my redis...
![image](https://user-images.githubusercontent.com/68145571/187185591-9aaf77e9-b8d3-4bcb-8fca-455bd4ce6f1c.png)
this is a totally wrong key....

Somehow your keying is messed up leading to if you do:

include: { data1, data2, data3} and then just update data1
the key of lets say
settings~data1~data2~data3 will not be updated
but the key of data1~data2~data3 will be.


notice i'm using dragonfly as it's way more performant then redis.



when invalidating you should probably do something liek this... `*settings~*`
![image](https://user-images.githubusercontent.com/68145571/187185995-7be13910-5f33-4682-b263-fd45458f387c.png)


as what you are doing `settings~*` will think there are none...
![image](https://user-images.githubusercontent.com/68145571/187186006-7f946117-ee2f-4edf-afc8-c96279cd4d68.png)



So i changed the code up to:
![image](https://user-images.githubusercontent.com/68145571/187186144-0c85f89f-f917-4329-941f-5fb58dfa7a56.png)


and then it WORKED!!

**Comment by Tomato6966** [comment]
I created a PR: https://github.com/Asjas/prisma-redis-middleware/pull/235
