### ISSUE TITLE
INFO & QUESTION

### ISSUE THREAD

**Issue by Tomato6966** [Asjas/prisma-redis-middleware#236]
So it works now... (After I did `FLUSHALL`)

Why is there sometimes an r:MODELNAME and k:MODELNAME tho?

and sometimes not?!

Can u explain that ?

Thanks
![image](https://user-images.githubusercontent.com/68145571/187193895-124cc368-cea1-4cb3-9b8a-f7b76fab863f.png)

**Comment by Asjas** [comment]
>Why is there sometimes an r:MODELNAME and k:MODELNAME tho?

It's how `async-cache-dedupe` stores the data.

https://github.com/mcollina/async-cache-dedupe
