### ISSUE TITLE
Provide a configuration option for skipping methods

### ISSUE THREAD

**Issue by filiptronicek** [Asjas/prisma-redis-middleware#27]
Hi there! Love the project, it's been awesome so far.

I would really appreciate if one could skip some methods so they wouldn't be cached (e.g. I would like to skip `findMany`). This could be a configuration option of `createPrismaRedisCache`, maybe having the inverse of this (an array of all **allowed** methods), would also benefit many projects I'm sure.

**Comment by Asjas** [comment]
You can now specify a `excludeCacheMethods` option to `createPrismaRedisCache` to exclude certain methods from being cached.
