### ISSUE TITLE
Make caching multiple models possible

### ISSUE THREAD

**Issue by filiptronicek** [Asjas/prisma-redis-middleware#28]
Currently (at least that's what is looks like to me), one can only cache one Prisma model at a time. It would be useful to make this option an array, and if an empty one or `undefined`is provided, it could cache all models (disable the check in https://github.com/Asjas/prisma-redis-middleware/blob/main/index.ts#L50).

**Comment by Asjas** [comment]
You can now specify an array of `models` to cache.
