### ISSUE TITLE
Query stuck at high traffic production app

### ISSUE THREAD

**Issue by maitrungduc1410** [Asjas/prisma-redis-middleware#377]
**Describe the bug**
We have a high traffic app which is running in production, in there the read throughput is usually ~30k-50k read/write queries/per second, 24/7. And we're facing a serious issue where read query is stuck randomly, without any reason.

Overview: we have 3 tables:

-`Order` (has a field name `orderNumber`)
- `Product`
- `OrderItem`: has a foreign key to `Order` and `Product`

The structure is simple.

Our flow is, before creating new order we need to check if product exist using `findFirst` and check if order number exist using `findFirst`

During peak hours, the 2 find queries failed randomly at about every 1 hour, they're stuck, never return.

Here are what I have tried:
- reduce `cacheTime` and `referencesTTL`, it improves a bit , but the error still happens after few hours
- remove `invalidation`: better than keeping invalidation, but error is still there
- completely disable caching: works fine, no issue at all

(I made change and observed during 1 week)

**Server:**
 - OS: Docker, Node 14 Alpine, NextJS 13
 - Browser: Chrome
 - Version: `"@prisma/client": "^4.5.0", "prisma": "^4.6.1", "prisma-redis-middleware": "^4.3.0"`

**Comment by maitrungduc1410** [comment]
just my guess, during peak hours, read/write is high, cache is set/invalidated over and over, and maybe (just guess), during a read query is trying to  find an index, somehow it's changed/removed, results in the query stuck

**Comment by lokize** [comment]
hi, just out of curiosity because I'm starting to use this middleware now, does the problem remain?

**Comment by maitrungduc1410** [comment]
Yes it still remains, I just give it another try last week and still its there and I had to disable it(again)

**Comment by lcdss** [comment]
Here we had the same issue using this middleware on production and it doesn't need high traffic to happen. We are still using it, but seriously thinking about removing it, as we couldn't find a way to fix the problem yet.

**Comment by victorbuttner** [comment]
same happening here, in production for no reason the app stucks stop responding, the redis server looks fine without CPU overload and high memory usage.
I noticed on my app metrics that before using the middleware the memory usage from the app increases a lot, sometimes causing memory leak crashes.

**Comment by lorenzobersano** [comment]
Same here, not even that much requests coming but some queries get randomly stuck: same query maybe works if app client is in 5G, doesn't when under wifi  🤷‍♂️

**Comment by cloverink** [comment]
Does the problem remain? How did you guys find the way out?

**Comment by lcdss** [comment]
In our case, we removed this middleware and later on, we ended up migrating to TypeORM, because of some unoptimized queries and limitations of Prisma. There was also an instability in the connection to the database, but that might just have been a misconfiguration.
