### ISSUE TITLE
Output validation failed

### ISSUE THREAD

**Issue by ckt1031** [Asjas/prisma-redis-middleware#382]
**Describe the bug**

The package is not turning the value back the **Date** when using redis as caching store and Datetime field in prisma, this will cause any validator like zod an error.

However, date value works in memory cache, redis does not

**To Reproduce**

Store Datetime value in prisma and using redis as caching, then validating the prisma data with zod date

**Expected behavior**

`Output validation failed`

**Screenshots**

![image](https://user-images.githubusercontent.com/65409152/218121958-31372ba5-7d54-4f82-b743-8f80ff7f12c4.png)

**Comment by yangricardo** [comment]
Also having a similar issue with Date. It seems to be a serialization problem. I don't know how the JSON is serialized or desserialized alongside Redis interaction, but be using SuperJSON library should help, as it handle Date object in a better way that simple JSON.stringify

**Comment by yangricardo** [comment]
> Also having a similar issue with Date. It seems to be a serialization problem. I don't know how the JSON is serialized or desserialized alongside Redis interaction, but be using SuperJSON library should help, as it handle Date object in a better way that simple JSON.stringify

@Asjas , seems that the library [async-cache-dedupe](https://github.com/mcollina/async-cache-dedupe) also suggests [superjson](https://github.com/blitz-js/superjson) to be used in the transformer customization

**Comment by markthethomas** [comment]
having the same issue - would like to use this library but not being able to store anything with a date....not ideal 😄 can try to open a PR to do the above possibly

**Comment by udonc** [comment]
async-cache-dedupe has an [issue](https://github.com/mcollina/async-cache-dedupe/issues/60) related to custom transformer options. If this issue is resolved, it might also be fixable.

**Comment by ckt1031** [comment]
This issue cna be solved if zod type is adding `coerce` to enable strings compatibility from dates and number value

**Comment by udonc** [comment]
I've created a pull request (#503) to address this issue. The PR introduces custom transformer options, which will allow for more flexible serialization and deserialization of cached data.
