### ISSUE TITLE
Redis storage is not supported in the browser

### ISSUE THREAD

**Issue by garenyondem** [Asjas/prisma-redis-middleware#466]
**Describe the bug**
Seeing the following error on Node.js v18.16.0

```
/app/node_modules/async-cache-dedupe/src/storage/index.js:36
throw new Error('Redis storage is not supported in the browser')

Error: Redis storage is not supported in the browser.
```

Running a backend api server in Docker container with node:18.16-buster-slim as base image.
Using ioredis to handle redis interactions. 
Prisma middleware is not the only place I use redis in, so I'm sure ioredis works and behaves fine.

I don't know why it thinks it is running in a browser, is there a workaround to this?

**Comment by Asjas** [comment]
Because your code is failing this test. https://github.com/mcollina/async-cache-dedupe/blob/main/src/util.js#L144

Closing as this is likely user issue and not related to this library.
